### ISSUE TITLE
password format

### ISSUE THREAD

**Issue by ForBTM** [jaimehgb/RaiWalletV2#15]
Could do you  tell  me  the password  format?
The AES256   is so difficult!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jaimehgb** [comment]
Well, I'd prefer you to try to find a flaw at some point of the encryption. Trying to bruteforce the password is something anyone can do 🤷‍♂️

**Comment by ForBTM** [comment]
Which part is encryption,
Can you provide the source code of the source server (the code in the repo seems not useful) and the database structure?
This problem，you know，makes me crazy and frustrated.........

**Comment by jaimehgb** [comment]
Read the readme :)
All you need is there
