### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by roosmaa** [jaimehgb/RaiWalletV2#3]
I can't find any information wrt licensing for this code. I would suggest adding a LICENSE file so that it's clear and that Github could also easily show the license that applies to this codebase.

**Comment by jaimehgb** [comment]
There you go :D 
https://github.com/jaimehgb/RaiWalletV2/commit/79307aea6f1da98a8fa85ff4d83df055e1f0ad83

(Messed up with the issue id :P )
