### ISSUE TITLE
Incorrect Transaction To\From Ids

### ISSUE THREAD

**Issue by sitefinitysteve** [jaimehgb/RaiWalletV2#7]
Was testing out the wallet with someone today sending 1 nano back and forth... so works great!  However the Transaction UI was showing To\From as my address, and on his end the To\From as his address.

For both of us re-logging in seems to have fixed the problem, showing the correct walletids again.

**Comment by JeffWScott** [comment]
I can confirm I also have this issues.

Logging in and out fixes it; until the next transaction.
