### ISSUE TITLE
Sent nano are not received at nanowallet.io wallet

### ISSUE THREAD

**Issue by ajayt6** [jaimehgb/RaiWalletV2#9]
Hi,
I sent some nano (0.000002 nano and 0.000003 ). THey are not received at nanowallet.io wallet. I have checked option for generating POW locally. The status is shown as : "Received, pending deposit to balance. (Make sure wallet is open and all blocks are downloaded)"

https://raiblocks.net/block/index.php?h=DC24AA90A8EEECB84CA36CD2F8556896A6EE40ABE5FB0E9F64AE10EB9000AE8A 

I think its an issue at nanowallet.io. Coorect me if i am wrong and it is an issue at the sender wallet.

**Comment by jaimehgb** [comment]
It appears as completed right now. I guess there was a delay somewhere :P 
Closing the issue.
